export const EstadoTurno = {
    DISPONIBLE: 'DISPONIBLE',
    RESERVADO: 'RESERVADO',
    CONFIRMADO: 'CONFIRMADO',
    RECHAZADO: 'RECHAZADO',
    CANCELADO: 'CANCELADO',
    REALIZADO: 'REALIZADO'
}
